export default function sitemap() {
  const base = "https://www.makoladigital.online";
  const now = new Date();
  return [
    { url: base, lastModified: now, changeFrequency: "daily", priority: 1 },
    { url: `${base}/search`, lastModified: now, changeFrequency: "daily", priority: 0.9 },
    { url: `${base}/sell`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${base}/auth/register`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/auth/login`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/blog`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${base}/blog/how-to-sell-online-ghana-2026`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/blog/top-things-to-buy-sell-makola-digital`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/blog/makola-digital-registered-ghanaian-company`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/blog/best-places-buy-second-hand-phones-ghana-2026`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/blog/how-to-spot-fake-sellers-online-ghana`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/blog/top-ways-make-money-online-ghana-2026`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/privacy`, lastModified: now, changeFrequency: "monthly", priority: 0.4 },
    { url: `${base}/terms`, lastModified: now, changeFrequency: "monthly", priority: 0.4 },
    { url: `${base}/delete-account`, lastModified: now, changeFrequency: "monthly", priority: 0.3 },
    { url: `${base}/catalogue`, lastModified: now, changeFrequency: "daily", priority: 0.6 },
    { url: `${base}/pricing`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${base}/contact`, lastModified: now, changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/category`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${base}/category/fashion`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${base}/category/electronics`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${base}/category/home-garden`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${base}/category/beauty-health`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${base}/category/food-beverages`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${base}/category/agriculture`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${base}/category/animals-pets`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${base}/category/arts-crafts`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${base}/category/vehicles`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${base}/category/property`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${base}/category/business-services`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${base}/category/tech-digital`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${base}/category/jobs`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${base}/category/education`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
    { url: `${base}/category/home-services`, lastModified: now, changeFrequency: "daily", priority: 0.8 },
  ];
}
